### ISSUE TITLE
Quick Start "FUN" Part 1

### ISSUE THREAD

**Issue by danpopnyc** [vaikas/sigstore-scaffolding#7]
**Env Details**
KIND= kind v0.11.1 go1.16.4 linux/amd64
KO= v0.9.3
Knative Serving = latest
K8s= 1.21.1
GO= go version go1.17.3 linux/amd64
Hardware OS = Ubuntu 20.04.2 LTS

**STEPS TO RECREATE:**

1) create a default cluster in kind and install [knative serving](https://knative.dev/docs/install/serving/install-serving-with-yaml/)
2) `run ko apply -BRf ./config`

Output of `kubectl get pods --all-namespaces`

![image](https://user-images.githubusercontent.com/22457772/149380452-90afe1fc-c9c0-4611-ab80-e84fc2239bc9.png)

Output of  `k get jobs --all-namespaces`

![image](https://user-images.githubusercontent.com/22457772/149381401-49198bc7-310f-415b-a230-4568d51b7d03.png)

**Issue(s):** 
ctlog-system

looks like ctlog-public-key not found? 

![image](https://user-images.githubusercontent.com/22457772/149381848-bdca3a50-bc48-4276-a28f-48399ef3a6c6.png)

Trillian-System 
Log Signer (Pod ImagePullBackoff issue) 
![image](https://user-images.githubusercontent.com/22457772/149380826-7cb71bc2-14c5-4d99-98b6-241cceac7024.png)

**Comment by vaikas** [comment]
And huge thanks for getting this into a standalone getting started!!!

**Comment by vaikas** [comment]
Also, if we can't create the CTLog TreeID (see my hunch above), that will cause the certs from not being created.

**Comment by danpopnyc** [comment]
redid the deployment using the /hack/install

ctlog-system createtree

`pop@popdc-node1:~/sigstore-scaffolding$ k logs createtree-bcpd2 | more
E0113 21:44:00.481448       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:00.629792       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:00.912999       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:01.379547       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:02.821839       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:04.716280       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc
= "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"`

ctlog-system createcert
` k logs -f createcerts-n6nr4
{"level":"error","ts":1642110552.9673417,"logger":"fallback","caller":"createcerts/main.go:71","msg":"No treeid yet, bailing","stacktrace":"main.main\n\tgithub.com/vaikas/sigstore-scaffolding/cmd/ctlog/createcerts/main.go:71\nruntime.main\n\truntime/proc.go:255"}`

rekor-system  createtree-4hwp8
`pop@popdc-node1:~/sigstore-scaffolding$ k logs createtree-4hwp8
E0113 21:44:00.821487       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:00.969500       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:01.252754       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"
E0113 21:44:01.719105       1 admin.go:55] Admin server unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup log-server.trillian-system.svc on 10.96.0.10:53: no such host"`

trillium-system log-server
` k logs log-server-00001-deployment-7566fb44fc-xvx2g log-server
Error from server (BadRequest): container "log-server" in pod "log-server-00001-deployment-7566fb44fc-xvx2g" is waiting to start: image can't be pulled`

trillium-system log-signer
` k logs log-signer-00001-deployment-5b57d8946c-n75qq log-signer
Error from server (BadRequest): container "log-signer" in pod "log-signer-00001-deployment-5b57d8946c-n75qq" is waiting to start: trying and failing to pull image`

**Comment by danpopnyc** [comment]
screenshot of all pods
![image](https://user-images.githubusercontent.com/22457772/149416517-cc81ba5f-64f8-4368-8563-ac1fefeda1f4.png)

screenshot of all svc
![image](https://user-images.githubusercontent.com/22457772/149416561-f56894f6-9648-422e-96cf-294be46c7289.png)

**Comment by vaikas** [comment]
ok, so it's a bit odd but the way I read this is that for some reason the images for trillian-system (both of them) are in imagepullbackoff, but for everything else things are successfully building just fine.

Can you describe a failing pod (say, log-signer?) and see what it thinks the image is and compare that with a say, rekor-system createtree pod that's running just fine.

Did any of this mayhaps get built differently or at different times? I guess one thing to try might be to just try (after grabbing the current state):
ko apply -BRf ./config/trillian

**Comment by danpopnyc** [comment]
describe log-signer 

`Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  29m                    default-scheduler  Successfully assigned trillian-system/log-signer-00001-deployment-5b57d8946c-n75qq to kind-worker
  Warning  Failed     28m                    kubelet            Failed to pull image "kind.local/trillian_log_signer:072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a": rpc error: code = Unknown desc = failed to pull and unpack image "kind.local/trillian_log_signer:072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a": failed to resolve reference "kind.local/trillian_log_signer:072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a": failed to do request: Head "https://kind.local/v2/trillian_log_signer/manifests/072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a": dial tcp: lookup kind.local: Temporary failure in name resolution
  Warning  Failed     28m                    kubelet            Error: ErrImagePull
  Normal   Pulled     28m                    kubelet            Container image "gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:48a1753de35ecbe060611aea9e95751e3e4851183c4373e65aa1b9410ea6e263" already present on machine
  Normal   Created    28m                    kubelet            Created container queue-proxy
  Normal   Started    28m                    kubelet            Started container queue-proxy
  Normal   BackOff    28m (x2 over 28m)      kubelet            Back-off pulling image "kind.local/trillian_log_signer:072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a"
  Warning  Failed     28m (x2 over 28m)      kubelet            Error: ImagePullBackOff
  Warning  Unhealthy  28m                    kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Pulling    28m (x2 over 29m)      kubelet            Pulling image "kind.local/trillian_log_signer:072eb78c8efea925dcf028948b2ad89e753263f301959d0f833a5b8636cf245a"
  Warning  Unhealthy  4m2s (x1339 over 28m)  kubelet            Readiness probe failed: Get "http://10.244.1.22:8013/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by danpopnyc** [comment]
rekor-system createtree 
![image](https://user-images.githubusercontent.com/22457772/149417594-695b6a7a-c2e2-4cee-af6a-c93d0cf162ec.png)

**Comment by danpopnyc** [comment]
as for if it was built differently.  i would say. i manually did the install and the second one was using your hack script.

**Comment by danpopnyc** [comment]
https://github.com/vaikas/sigstore-scaffolding/pull/9  looks like will address the issues we were seeing.

**Comment by vaikas** [comment]
Woot Woot!!!
